Block device tags
spinnaker/deck pull request #8911
Opened 2021-02-12 00:27 UTC by jorgebee65

This feature adds a Volume section in the Deploy Wizard which allows to add one ore more volumes to an instance and also add Tags which applies to the list of volumes. Dependency on this other [PR](https://github.com/spinnaker/clouddriver/pull/5244)

![volumes](https://githubprimages.s3-us-west-2.amazonaws.com/volumes.png)

2021-04-29 17:52 UTC, iandelahorne commented on app/scripts/modules/amazon/src/serverGroup/configure/serverGroupConfiguration.service.ts
> +  private volumeTypes = ['gp2', 'st1', 'io1', 'sc1'];
```suggestion
  private volumeTypes = ['gp2', 'gp3', 'st1', 'io1', 'io2', 'sc1'];
```

`gp3` is the new general-purpose volume type from AWS. This is only available if you're using LaunchTemplates. 
`io2` is their new provisioned IO volume type, only available in preview currently on r5b instances.
 (see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html)

2021-07-22 19:45 UTC, christopherthielen requested changes
thanks for migrating this to Formik.  I have a couple minor requests then I think it's good to go.

2021-07-22 19:45 UTC, christopherthielen commented on packages/amazon/src/serverGroup/configure/wizard/pages/volumes/ServerGroupVolumes.tsx
> +        </div>
This should use a `FormikFormField` and a `MapEditorInput` which would also make the `validate` and `tagsChanged functions unnecessary

2021-07-22 19:45 UTC, christopherthielen commented on packages/amazon/src/serverGroup/configure/wizard/pages/volumes/VolumeEditor.tsx
> +
I don't think this function gets called ever, and it is also a noop, so might as well remove it

2025-10-02 03:38 UTC, closed without merging