feat(core/Executions): Make component overridable
spinnaker/deck pull request #9002
Opened 2021-03-17 21:47 UTC by bbrina

## What does this PR do?
Adds code for the Executions component to be overridable

## Notes
A test is failing and I'm not quite sure what's wrong with it

```
✖ 1 test failed

FAILED TESTS:
  <Executions/>
    ✖ should not set loading flag to false until executions and pipeline configs have been loaded
      Chrome 89.0.4389 (Mac OS X 10.15.7)
    Error: ReactWrapper::state() can only be called on class components
        at ReactWrapper.state (webpack:///./node_modules/enzyme/build/ReactWrapper.js?:1076:17)
        at UserContext.eval (webpack:///./app/scripts/modules/core/src/pipeline/executions/Executions.spec.tsx?:51:26)
        at <Jasmine>
```

2021-03-23 17:28 UTC, dogonthehorizon approved these changes

2021-03-23 19:16 UTC, christopherthielen requested changes

2021-03-23 19:16 UTC, christopherthielen commented on app/scripts/modules/core/src/pipeline/executions/Executions.tsx
> +export default Executions;
Deck doesn't use default exports, please remove this.
```suggestion
```

2021-03-23 19:16 UTC, christopherthielen commented on app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/TitusMapLayout.less
> +  flex: auto;
please revert

2021-03-23 19:16 UTC, christopherthielen commented on app/scripts/modules/titus/src/serverGroup/configure/wizard/pages/ServerGroupParameters.tsx
> +import { AccountTag, Application, CheckboxInput, ChecklistInput, FormikFormField, FormValidator, HelpField, IFormInputProps, IWizardPageComponent, LayoutProvider, MapEditorInput, PlatformHealthOverri
these two other changes by the auto-formatter or linter are unrelated to this PR, please remove them (feel free to file a separate PR if you want)

2021-03-23 19:16 UTC, christopherthielen commented on app/scripts/modules/core/src/pipeline/executions/Executions.tsx
> +@Overridable('createExecutions')
```suggestion
@Overridable('PipelineExecutions')
```

2021-03-24 01:29 UTC, christopherthielen commented
@bbrina we can change the failing unit test to look for the spinner instead of inspecting component state.

```jsx
  it('should not set loading flag to false until executions and pipeline configs have been loaded', (done) => {
    initializeApplication();
    expect(component.find(Spinner).length).toBe(1);
    application.executions.dataUpdated();
    application.pipelineConfigs.dataUpdated();
    scope.$digest();
    setTimeout(() => {
      component.setProps({});
      expect(component.find(Spinner).length).toBe(0);
      done();
    }, 100);
  });
```

2021-03-24 20:02 UTC, bbrina commented
Thanks @christopherthielen!

2021-03-24 21:58 UTC, christopherthielen approved these changes

2021-03-24 22:08 UTC, merged