feat(Blue/Green): Add warning label for Deployment kind.
spinnaker/deck pull request #9928
Opened 2022-12-05 14:06 UTC by DanielaS12

Add warning label for Deployment kind. Screenshots bellow:

Deployment
<img width="943" alt="image" src="https://user-images.githubusercontent.com/111055962/205656541-7a1d0a74-1e8a-41e6-8e63-71502d322ea9.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/111055962/205656576-c79b449a-89d3-4890-adc6-0ebe4ff51b20.png">

ReplicaSet
<img width="943" alt="image" src="https://user-images.githubusercontent.com/111055962/205656051-b8e3267b-3d98-447a-a5f1-18f23ff14973.png">
<img width="943" alt="image" src="https://user-images.githubusercontent.com/111055962/205656086-9cbe5fe9-b0ec-4d13-889a-7fe27afaf020.png">

2022-12-06 13:03 UTC, ovidiupopa07 requested changes
can you please add some unit tests please? Similar to the ones I added for the blue green change

2022-12-07 17:14 UTC, ovidiupopa07 approved these changes

2022-12-09 13:23 UTC, DanielaS12 commented
@dogonthehorizon Could you please merge this pr?

2022-12-12 16:21 UTC, dogonthehorizon approved these changes

2022-12-12 16:21 UTC, merged

2023-03-03 18:19 UTC, link108 commented
reverting this due to reverting the feature, see https://github.com/spinnaker/clouddriver/pull/5865#issuecomment-1426315921